name = "haskell-spec"
version = "0.1.0"
defaultTargets = ["haskell-spec"]

[[lean_lib]]
name = "HaskellSpec"

[[lean_exe]]
name = "haskell-spec"
root = "Main"

[[require]]
name = "veriflex"
git = "https://github.com/haskell-spec/veriflex.git"
rev = "07b968faf0c018fccc1faa1dec46a059ac773a0a"